#!/bin/bash
# Azure Local Deployment Script
# Generated by Odin for Azure Local

# Variables
# Tenant ID - Required when authenticating across multiple tenants
TENANT_ID="2fab734c-3581-4c94-8c73-8f6dbee0ab86"
SUBSCRIPTION_ID="859c4879-999f-4cd5-a9bb-df171e8d1ad8"
RESOURCE_GROUP="azljkt01rg"
DEPLOYMENT_NAME="azljkt01dep"
LOCATION="southeastasia"  # Change as needed
TEMPLATE_FILE="odin-template.json"
PARAMETERS_FILE="odin-parameters.json"

# Login to Azure (with Tenant ID)
az login --tenant "2fab734c-3581-4c94-8c73-8f6dbee0ab86"

# Set subscription
az account set --subscription "$SUBSCRIPTION_ID"

# Create resource group if it doesn't exist
az group create \
    --name "$RESOURCE_GROUP" \
    --location "$LOCATION"

# Deploy the ARM template
echo "Starting deployment: $DEPLOYMENT_NAME"
az deployment group create \
    --name "$DEPLOYMENT_NAME" \
    --resource-group "$RESOURCE_GROUP" \
    --template-file "$TEMPLATE_FILE" \
    --parameters "@$PARAMETERS_FILE" \
    --verbose

echo "Deployment completed successfully!"
