# Azure Local Deployment Script
# Generated by Odin for Azure Local

# Variables
# Tenant ID - Required when authenticating across multiple tenants
$tenantId = "2fab734c-3581-4c94-8c73-8f6dbee0ab86"
$subscriptionId = "859c4879-999f-4cd5-a9bb-df171e8d1ad8"
$resourceGroupName = "azljkt01rg"
$deploymentName = "azljkt01dep"
$location = "southeastasia"  # Change as needed
$templateFile = "odin-template.json"
$parametersFile = "odin-parameters.json"

# Connect to Azure (with Tenant ID)
Connect-AzAccount -TenantId "2fab734c-3581-4c94-8c73-8f6dbee0ab86"

# Set subscription context
Set-AzContext -SubscriptionId $subscriptionId

# Create resource group if it doesn't exist
$rg = Get-AzResourceGroup -Name $resourceGroupName -ErrorAction SilentlyContinue
if (-not $rg) {
    Write-Host "Creating resource group: $resourceGroupName"
    New-AzResourceGroup -Name $resourceGroupName -Location $location
}

# Deploy the ARM template
Write-Host "Starting deployment: $deploymentName"
New-AzResourceGroupDeployment `
    -Name $deploymentName `
    -ResourceGroupName $resourceGroupName `
    -TemplateFile $templateFile `
    -TemplateParameterFile $parametersFile `
    -Verbose

Write-Host "Deployment completed successfully!"
